version: "3"
name: nodejs_services

services:
  mongo:
    build: mongo
    env_file: mongo/.env.production
    volumes:
      - mongo:/data/db
    ports:
      - ${MONGO_HOST_PORT}:${MONGO_CONTAINER_PORT}

  user_registration:
    depends_on:
      - mongo
    build:
      context: node
      secrets:
        - gpr_read_token
    env_file: node/.env.production
    ports:
      - ${NODE_HOST_PORT}:${NODE_CONTAINER_PORT}

volumes:
  mongo:

secrets:
  # Token to read from GitHub Package Registry
  gpr_read_token:
    file: node/gpr_read_token.secret
