name: nodejs_services

services:
  mongo:
    build: mongo
    env_file: mongo/.env
    volumes:
      - mongo:/data/db
    ports:
      - ${MONGO_HOST_PORT}:${MONGO_CONTAINER_PORT}

  # user_registration:
  #   build: node
  #   env_file: node/.env
  #   ports:
  #     - ${NODE_HOST_PORT}:${NODE_CONTAINER_PORT}

volumes:
  mongo:
